apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-congressmemberapi
  labels:
    app: congressmemberapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: congressmemberapi
  template:
    metadata:
      labels:
        app: congressmemberapi
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
