version: "3.4"
services:
  congressmemberapi:
    image: twitterbotacr.azurecr.io/twitter-bot/congressmemberapi
    build:
      context: ./
      dockerfile: ./CongressMemberAPI/Dockerfile
    container_name: congressmemberapi
    environment:
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID
      - ASPNETCORE_ENVIRONMENT
    ports:
      - "5269:80"
  membertracker:
    image: twitterbotacr.azurecr.io/twitter-bot/membertracker
    build:
      context: ./
      dockerfile: ./MemberTracker/Dockerfile
    container_name: membertracker
    environment:
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID
      - ASPNETCORE_ENVIRONMENT