version: "3.4"
services:
  congressmemberapi:
    image: twitterbotacr.azurecr.io/twitter-bot/congressmemberapi:1.0.0
    build:
      context: ./
      dockerfile: ./CongressMemberAPI/Dockerfile
    container_name: congressmemberapi
    environment:
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID
      - ASPNETCORE_ENVIRONMENT
    ports:
      - "5269:80"
  syncmemberdbjob:
    image: twitterbotacr.azurecr.io/twitter-bot/syncmemberdbjob:1.0.0
    build:
      context: ./
      dockerfile: ./SyncMemberDbJob/Dockerfile
    container_name: syncmemberdbjob
    environment:
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID
      - ASPNETCORE_ENVIRONMENT