apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.managedIdentity.clientId }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ .Values.managedIdentity.name }}
  namespace: {{ .Release.Namespace }}
