apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  schedule: "0 0 16 * *"
  jobTemplate:
    spec:
      template:
        metadata:
         labels:
          azure.workload.identity/use: "true"
        spec:
          serviceAccountName: {{ .Values.managedIdentity.name }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: Always
            env:
              - name: ASPNETCORE_ENVIRONMENT
                value: {{ .Values.aspNetCore.environment }}
          restartPolicy: OnFailure
