name: Push Container Images to Azure Container Registry

on:
  workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout main branch'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker compose build
        docker compose push
