name: 'CongressMemberAPI'

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      # any time chart is updated, means app has been updated
      - 'charts/congressmember-api/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    environment: ${{ fromJSON('["development", "production"]')[github.ref == 'refs/heads/main'] }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Deploy to Azure Kubernetes Service'
      uses: ./.github/workflows/deploy-aks.yml
      with:
        dockerImage: 'congressmemberapi'
        dockerfileDir: 'CongressMemberAPI'
        helmChart: 'congressmember-api'
