name: 'SyncMemberDbJob'

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      # any time chart is updated, means app has been updated
      - 'charts/sync-member-db-job/**'
  workflow_dispatch:

jobs:
  aks-deploy:
    uses: ./.github/workflows/deploy-aks.yml
    with:
      dockerImage: 'syncmemberdbjob'
      dockerfileDir: 'SyncMemberDbJob'
      helmChart: 'sync-member-db-job'
