name: 'CongressMemberAPI'

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      # any time chart is updated, means app has been updated
      - 'charts/congressmember-api/**'
  workflow_dispatch:

jobs:
  aks-deploy:
    uses: ./.github/workflows/deploy-aks.yml
    with:
      dockerImage: 'congressmemberapi'
      dockerfileDir: 'CongressMemberAPI'
      helmChart: 'congressmember-api'
