name: 'sentiment_tweet_job'

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      # any time chart is updated, means app has been updated
      - 'charts/sentiment-tweet-job/**'
  workflow_dispatch:

jobs:
  aks-deploy:
    environment: ${{ fromJSON('["development", "production"]')[github.ref == 'refs/heads/main'] }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout branch'
      uses: actions/checkout@v3

    - name: 'Deploy to Azure Kubernetes Service'
      uses: ./.github/workflows/deploy-aks.yml
      with:
        dockerImage: 'sentimenttweetjob'
        dockerfileDir: 'sentiment_tweet_job'
        helmChart: 'sentiment-tweet-job'
