name: 'sentiment_tweet_job'

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      # any time chart is updated, means app has been updated
      - 'charts/sentiment-tweet-job/**'
  workflow_dispatch:

jobs:
  aks-deploy:
    uses: ./.github/workflows/deploy-aks.yml
    with:
      dockerImage: 'sentimenttweetjob'
      dockerfileDir: 'sentiment_tweet_job'
      helmChart: 'sentiment-tweet-job'
